### ISSUE TITLE
sign is random colours that dont show in codewalker

### ISSUE THREAD

**Issue by poarra** [MalibuTechTeam/iak_custom_sign#1]
all the files in /template are also all white i made them all white and still is random colours

**Comment by MalibuTechTeam** [comment]
Follow this guide https://www.youtube.com/watch?v=OFNpN5RanzE&t=1s or join our discord and read post in community-help

**Comment by poarra** [comment]
guide literally doesnt show anything related to the colours and community help doesnt reply
